version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: central
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: posgtres
    ports:
      - "5432:5432"

  backend:
    container_name: central_app
    build:
      context: ./master-lib
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://admin:posgtres@postgres:5432/central?sslmode=disable
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres
