apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: central-pvc
spec:
  volumeName: central-postgres
  selector:
    matchLabels:
      name: central-postgres
  resources:
    requests:
      storage: 1Gi 
  accessModes:
    - ReadWriteOnce
