apiVersion: v1
kind: PersistentVolume
metadata:
  name: central-postgres
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data-kube/central"
